-- Bingo Live Guest WebRTC signaling schema — REVIEW ONLY, NOT EXECUTED
-- Host + one guest. Supabase Realtime carries signaling/state; WebRTC carries media.

create table if not exists public.bingo_live_guest_requests (
  id uuid primary key default gen_random_uuid(),
  live_id text not null,
  host_id uuid not null references auth.users(id) on delete cascade,
  guest_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined','left','removed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists bingo_live_guest_one_active
on public.bingo_live_guest_requests(live_id, guest_id)
where status in ('pending','accepted');

create table if not exists public.bingo_live_signals (
  id bigint generated by default as identity primary key,
  live_id text not null,
  request_id uuid not null references public.bingo_live_guest_requests(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  signal_type text not null check (signal_type in ('offer','answer','ice','leave','remove')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists bingo_live_signals_recipient_idx
on public.bingo_live_signals(recipient_id, live_id, created_at);

alter table public.bingo_live_guest_requests enable row level security;
alter table public.bingo_live_signals enable row level security;

drop policy if exists "live request participants read" on public.bingo_live_guest_requests;
create policy "live request participants read" on public.bingo_live_guest_requests
for select to authenticated using (auth.uid() = host_id or auth.uid() = guest_id);

drop policy if exists "guest creates own live request" on public.bingo_live_guest_requests;
create policy "guest creates own live request" on public.bingo_live_guest_requests
for insert to authenticated with check (auth.uid() = guest_id and host_id <> guest_id);

drop policy if exists "host or guest updates request" on public.bingo_live_guest_requests;
create policy "host or guest updates request" on public.bingo_live_guest_requests
for update to authenticated using (auth.uid() = host_id or auth.uid() = guest_id)
with check (auth.uid() = host_id or auth.uid() = guest_id);

drop policy if exists "signal participants read" on public.bingo_live_signals;
create policy "signal participants read" on public.bingo_live_signals
for select to authenticated using (auth.uid() = sender_id or auth.uid() = recipient_id);

drop policy if exists "sender creates signal" on public.bingo_live_signals;
create policy "sender creates signal" on public.bingo_live_signals
for insert to authenticated with check (
  auth.uid() = sender_id
  and exists (
    select 1 from public.bingo_live_guest_requests r
    where r.id = request_id and r.live_id = bingo_live_signals.live_id
      and r.status = 'accepted'
      and auth.uid() in (r.host_id, r.guest_id)
      and recipient_id in (r.host_id, r.guest_id)
      and recipient_id <> sender_id
  )
);

-- Realtime publication: run only if not already added.
-- alter publication supabase_realtime add table public.bingo_live_guest_requests;
-- alter publication supabase_realtime add table public.bingo_live_signals;
