const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const uid='11111111-1111-4111-8111-111111111111',post='22222222-2222-4222-8222-222222222222';
const calls=[],notices=[];let failSave=false;
const values={vacTitle:'Real vacancy',vacCompany:'Bingo Test',vacDescription:'A saved vacancy',vacCounty:'Nairobi',vacExperience:'Entry'};
const ctx={console,crypto:require('node:crypto').webcrypto,Map,Set,HTMLVideoElement:class{},MutationObserver:class{observe(){}},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},localStorage:{getItem(){return null},setItem(){}},document:{body:{},visibilityState:'visible',querySelectorAll:()=>[],querySelector:()=>null,getElementById:id=>values[id]===undefined?null:{value:values[id]},addEventListener(){}},state:{view:'home',user:{id:uid},isLoggedIn:true,jobs:[{id:'local-only'}],spareParts:[],listings:[{id:1,_localDemo:true},{id:post,_fromDb:true,status:'published'}]},esc:String,money:String,bingoSafeMediaAttr:String,aaProfilePhoto:String,toast:x=>notices.push(x),openAuth(){},confirm:()=>true,aaPartFiltered:()=>[],aaIsFollowing:()=>false,aaMediaType:x=>x.mediaType||'photo',aaVideoUrl:x=>x.videoUrl||'',aaTopics:()=>[],aaProperties:()=>[],aaFoods:()=>[],aaBpItems:()=>[],aaBpTileHTML:x=>`<div data-canon="${x.kind}:${x.id}"></div>`,aaTopicPostCardHTML:x=>'<article></article>',aaMixedFeedCardHTML:x=>'<section></section>',aaMixedFeedItems:()=>[{kind:'vehicle',id:post,mediaType:'photo'},{kind:'topic',id:'t',feed_media_type:'video'},{kind:'food',id:'f',feed_media_type:'video',feed_media:'clip'}],aaCanonOpen(){},aaPublicTopicsFeedHTML:()=>'<section></section>',aaFoodActive:x=>x.status==='published',aaWallListingCardHTML:()=>'<article></article>',aaFeedDescExcerptHTML:String,aaMemberDisplayName:()=>'',aaResolveMemberMeta:()=>({}),detailsHTML:()=>'<section></section>',aaPropertyDetailHTML:()=>'',aaSpareDetailsHTML:()=>'',jobHTML:()=>'',aaFoodBusinessProfileHTML:()=>'',aaOpenVideoLightbox(){},aaOpenPhotoLightbox(){},aaHomeOverlayOpen:()=>false,aaPauseAllFeedVideos(){},render(){},aaLoadVehicles:async()=>{},aaLoadProperties:async()=>{},aaLoadFoods:async()=>{},aaIsOwnJob:x=>x.userId===uid,aaOpenSpareDetails(){},openJob(){},aaFeedUpdateSoundBtn(){},aaFeedWantsSound:()=>false,aaOwnProfileName:()=>'',aaTopicMediaSrc:x=>x.url};
ctx.sellerHTML=()=>'<section>Identity</section>';ctx.window=ctx;
ctx.sb={auth:{getUser:async()=>({data:{user:{id:uid}}})},rpc:async(name,args)=>{calls.push({name,args});return {data:name==='bingo_media_counts'?[{post_type:'topic',post_id:post,view_count:1,watch_count:0,photo_count:0}]:true}},from(name){return {upsert(row){calls.push({name,row});return {select:()=>({single:async()=>failSave?{error:{message:'Permission denied'}}:{data:{id:row.id}}})}},select:()=>({order:async()=>({data:[]})})}}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/../media-service/frontend.js','utf8'),ctx);
(async()=>{
 assert.equal(ctx.state.listings.length,1,'legacy samples/local drafts must not populate public feed');assert.equal(ctx.state.jobs.length,0,'local-only jobs must not masquerade as cloud posts');
 ctx.state.spareParts=[{id:'spare',_fromDb:true,status:'published',sellerId:uid,photos:['photo'],title:'Item'}];ctx.state.jobs=[{id:'job',_fromDb:true,status:'Published',userId:uid,title:'Vacancy'}];
 assert.equal(ctx.aaMixedFeedItems().length,5,'published categories share Home registry');ctx.state.homeMediaFilter='videos';assert.equal(ctx.aaMixedFeedItems().length,2,'video filter excludes photos and text');ctx.state.homeMediaFilter='photos';assert.equal(ctx.aaMixedFeedItems().length,3);ctx.state.homeMediaFilter='all';
 assert(ctx.aaPublicTopicsFeedHTML().includes('spare:spare'),'category posts reach Wall');assert.equal(ctx.aaBpItems({},[],uid).length,2,'category posts reach original owner profile');
 await ctx.BingoMedia.record({type:'topic',id:post},'view');await ctx.BingoMedia.record({type:'topic',id:post},'view');assert.equal(calls.filter(x=>x.name==='bingo_record_media_event').length,1,'a repeated view must not create another request');
 await ctx.publishVacancyRecord();const saved=calls.find(x=>x.name==='bingo_category_listings'&&x.row);assert.equal(saved.row.user_id,uid);assert.equal(saved.row.status,'published');assert(saved.row.payload.description==='A saved vacancy');
 failSave=true;await ctx.publishVacancyRecord();assert(notices.at(-1).includes('Permission denied'),'publishing must report actual save failure');
 console.log('PASS: public source filtering, Home/Wall/profile distribution, media filters, deduplication, authenticated persistence request and real save errors.');
})().catch(e=>{console.error(e);process.exitCode=1});
