/* Bingo reusable sounds: real Supabase records; no demo identities or local-only attribution. */
(function(){
'use strict';
const cache=new Map(),urls=new Map();let chosen=null,processed=false,modal=null,loading=false,cameraStream=null,recorder=null,captureKind="",cancelCapture=false;
const ident=x=>esc(JSON.stringify(String(x||'')));
const fail=e=>toast('Sound: '+String(e?.message||e),'error');
function removeDialog(){cancelCapture=true;if(recorder?.state==='recording')recorder.stop();cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;modal?.querySelectorAll('audio,video').forEach(x=>x.pause());modal?.remove();modal=null}
function show(title,body){removeDialog();modal=document.createElement('dialog');modal.id='bingoSoundDialog';modal.className='bingo-sound-dialog';modal.innerHTML='<header><b>'+esc(title)+'</b><button type="button" aria-label="Close sound window" onclick="BingoSounds.close()">×</button></header>'+body;document.body.appendChild(modal);modal.addEventListener('cancel',removeDialog);modal.addEventListener('close',()=>{modal.querySelectorAll('audio,video').forEach(x=>x.pause());modal.remove()});modal.showModal()}
function credit(s){const m=aaTopicAuthorMeta({authorId:s.original_uploader_id});return '<span>♫ '+esc(s.title)+'</span><button type="button" onclick="BingoSounds.close();openSeller('+ident(s.original_uploader_id)+')">Original sound · '+esc(m?.name||'View original profile')+'</button>'}
function audioUrl(s){if(urls.has(s.id))return urls.get(s.id);if(!urls.has('pending:'+s.id)){urls.set('pending:'+s.id,true);sb.storage.from('sound-audio').createSignedUrl(s.audio_path,1800).then(({data,error})=>{if(error){urls.delete('pending:'+s.id);return}urls.set(s.id,data.signedUrl)})}return ''}
async function refresh(){if(!sb||loading)return;loading=true;try{const {data,error}=await sb.from('bingo_sounds').select('*').order('created_at',{ascending:false}).limit(500);if(error)throw error;cache.clear();for(const s of data||[])cache.set(s.id,s)}finally{loading=false}}
function bar(t){const hasVideo=(t.media||[]).some(m=>m.type==='video');if(!t.soundId&&!hasVideo)return '';const s=cache.get(t.soundId);return '<div class="bingo-sound-bar" onclick="event.stopPropagation()">'+(s?credit(s):'<span>♫ Original sound</span>')+'<button type="button" onclick="BingoSounds.open('+ident(t.id)+')">'+(s?'Use this sound':'Check sound')+'</button></div>'}
async function online(){const r=await sb.rpc('bingo_sound_processor_online');if(r.error)throw r.error;return !!r.data}
async function loadAudio(s){if(!urls.has(s.id)){const r=await sb.storage.from('sound-audio').createSignedUrl(s.audio_path,1800);if(r.error)throw r.error;urls.set(s.id,r.data.signedUrl)}return urls.get(s.id)}
async function open(id){try{await refresh();const t=aaTopics().find(x=>String(x.id)===String(id));if(!t)throw Error('This post is unavailable');if(t.soundId&&!cache.has(t.soundId)){const r=await sb.from('bingo_sounds').select('*').eq('id',t.soundId).maybeSingle();if(r.error)throw r.error;if(r.data)cache.set(r.data.id,r.data)}const s=cache.get(t.soundId);if(s){const src=await loadAudio(s);show('Use this sound?',credit(s)+(src?'<audio controls src="'+bingoSafeMediaAttr(src)+'"></audio>':'<p>Loading audio… close and reopen shortly.</p>')+'<p>Choose your media, then preview in the existing Bingo composer.</p><div class="bingo-sound-choices">'+['video','photo','record','camera'].map((v,i)=>'<button class="btn btn-gold" onclick="BingoSounds.choose('+ident(s.id)+','+ident(v)+')">'+['Upload video','Upload photo','Record video','Take photo'][i]+'</button>').join('')+'</div><button class="btn" onclick="BingoSounds.posts('+ident(s.id)+')">View posts using this sound</button>');return}
if(!state.isLoggedIn){openAuth('login');return}
if(!await online()){show('Sound processing not yet available','<p>This video stays available to watch. Its sound cannot receive reusable credit until Bingo’s audio-recognition processor is running.</p><p>No new uploader credit has been accepted.</p>');return}
const r=await sb.rpc('bingo_queue_sound',{p_topic:id});if(r.error)throw r.error;show('Checking original sound','<p>Bingo is checking the audio against saved sounds. Original credit is assigned only after recognition.</p><button class="btn" onclick="BingoSounds.reload()">Check again</button>')
}catch(e){fail(e)}}
async function choose(id,kind){if(!state.isLoggedIn){removeDialog();openAuth('login');return}chosen=cache.get(id);processed=false;removeDialog();aaFocusWallComposer();if(kind==='record'||kind==='camera'){camera(kind);return}const input=document.createElement('input');input.type='file';input.accept=(kind==='video'||kind==='record')?'video/*':'image/*';if(kind==='record'||kind==='camera')input.setAttribute('capture','environment');input.onchange=()=>{const f=input.files[0];if(!f)return;const err=aaValidateTopicMediaFile(f);if(err){fail(Error(err));return}aaSetTopicMediaSelection([f]);render();BingoSounds.preview()};input.click()}
async function camera(kind){captureKind=kind;show(kind==='record'?'Record video with selected sound':'Take a photo with selected sound','<video id="bingoSoundCamera" muted autoplay playsinline></video><button class="btn btn-gold" onclick="BingoSounds.capture()">'+(kind==='record'?'Start recording':'Take photo')+'</button><p>Selected sound will be added after processing.</p>');cancelCapture=false;try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});document.getElementById('bingoSoundCamera').srcObject=cameraStream}catch(e){fail(Error('Camera access failed: '+e.message));removeDialog()}}
function captured(f){removeDialog();aaSetTopicMediaSelection([f]);processed=false;render();preview()}
function capture(){try{const v=document.getElementById('bingoSoundCamera');if(!cameraStream||!v)throw Error('Camera is not ready');if(captureKind==='camera'){const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;if(!c.width)throw Error('Wait for the camera preview');c.getContext('2d').drawImage(v,0,0);c.toBlob(b=>{if(b)captured(new File([b],'bingo-camera.png',{type:'image/png'}))},'image/png');return}if(recorder?.state==='recording'){recorder.stop();return}const parts=[];recorder=new MediaRecorder(cameraStream);recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data)};recorder.onstop=()=>{if(cancelCapture)return;const mime=recorder.mimeType||'video/webm';captured(new File(parts,'bingo-recording.'+(mime.includes('mp4')?'mp4':'webm'),{type:mime}))};recorder.start();modal.querySelector('.btn').textContent='Stop recording';const active=recorder;setTimeout(()=>{if(active.state==='recording')active.stop()},180000)}catch(e){fail(e)}}
function composer(){if(state.topicEditId)return '';return '<div class="bingo-sound-composer">'+(chosen?credit(chosen)+'<button class="btn" type="button" onclick="BingoSounds.preview()">Preview with sound</button><button class="btn" type="button" onclick="BingoSounds.clear()">Remove sound</button>':'<button type="button" class="btn" onclick="BingoSounds.library()">♫ Saved sounds</button>')+'<button type="button" class="btn" onclick="BingoSounds.jobs()">Sound processing</button></div>'}
function preview(){if(!chosen)return;const f=aaTopicMediaSelection()[0];if(!f){toast('Select a photo or video first');return}const src=audioUrl(chosen),url=aaTopicMediaObjectUrl(f);show('Preview with selected sound',credit(chosen)+(/^video\//.test(f.type)?'<video id="bingoSoundPreviewMedia" muted playsinline controls src="'+bingoSafeMediaAttr(url)+'"></video>':'<img alt="Selected photo" src="'+bingoSafeMediaAttr(url)+'">')+(src?'<audio id="bingoSoundPreviewAudio" controls src="'+bingoSafeMediaAttr(src)+'"></audio><button class="btn btn-gold" onclick="BingoSounds.playPreview()">Play with sound</button>':'<p>Audio is loading. Reopen this preview shortly.</p>')+'<p>Selected sound replaces the video audio. Publish creates one media file after processing.</p>')}
async function playPreview(){const v=document.getElementById('bingoSoundPreviewMedia'),a=document.getElementById('bingoSoundPreviewAudio');try{if(v){v.muted=true;v.currentTime=0;v.onpause=()=>a?.pause();v.onended=()=>a?.pause()}if(a){a.currentTime=0;a.loop=true}await Promise.all([v?.play(),a?.play()])}catch(e){fail(e)}}
async function library(){try{await refresh();show('Saved sounds',[...cache.values()].map(s=>'<div class="bingo-sound-bar">'+credit(s)+'<button class="btn" onclick="BingoSounds.open('+ident(s.source_topic_id)+')">Use</button></div>').join('')||'<p>No recognised sounds are saved yet. Sounds appear here after the audio processor verifies original videos.</p>')}catch(e){fail(e)}}
async function jobs(){if(!state.isLoggedIn){openAuth('login');return}try{const r=await sb.from('bingo_sound_jobs').select('*').eq('user_id',state.user.id).order('created_at',{ascending:false}).limit(30);if(r.error)throw r.error;show('Your sound processing',(r.data||[]).map(j=>'<div class="bingo-sound-bar"><span>'+esc(j.kind==='recognise'?'Original sound check':'Media with selected sound')+' · '+esc(j.state)+'</span>'+ (j.error?'<small>'+esc(j.error)+'</small>':'')+(j.kind==='compose'&&j.state==='ready'?'<button class="btn btn-gold" onclick="BingoSounds.resume('+ident(j.id)+')">Preview & publish</button>':'')+'</div>').join('')||'<p>No sound processing jobs yet.</p>')}catch(e){fail(e)}}
async function resume(id){try{const r=await sb.from('bingo_sound_jobs').select('*').eq('id',id).eq('user_id',state.user.id).single();if(r.error)throw r.error;const j=r.data;if(j.state!=='ready'||!j.output_path)throw Error('Processing has not completed');await refresh();const s=cache.get(j.sound_id);if(!s)throw Error('The sound is no longer available');const out=await sb.storage.from('sound-inputs').download(j.output_path);if(out.error)throw out.error;await loadAudio(s);chosen=s;processed=true;removeDialog();aaFocusWallComposer();aaSetTopicMediaSelection([new File([out.data],'bingo-with-sound.mp4',{type:'video/mp4'})]);state.topicDraft.body=j.caption;render();preview()}catch(e){fail(e)}}
async function posts(id){await aaLoadBingoWall();show('Posts using this sound',aaTopics().filter(t=>t.soundId===id).map(t=>'<button class="btn" onclick="BingoSounds.close();aaOpenTopicPost('+ident(t.id)+')">'+esc(t.title||'View post')+'</button>').join('')||'<p>No public posts are available.</p>')}
async function upload(f,path){const {data:{session},error}=await sb.auth.getSession();if(error||!session)throw Error('Sign in again before uploading');return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();let last=Date.now();let done=false;const timer=setInterval(()=>{if(!done&&Date.now()-last>90000){xhr.abort();reject(Error('Upload stalled for 90 seconds. Your draft is retained.'))}},1000);xhr.open('POST',SUPABASE_URL+'/storage/v1/object/sound-inputs/'+path);xhr.setRequestHeader('Authorization','Bearer '+session.access_token);xhr.setRequestHeader('apikey',SUPABASE_PUBLISHABLE_KEY);xhr.setRequestHeader('Content-Type',f.type);xhr.upload.onprogress=e=>{last=Date.now();if(e.lengthComputable)toast('Sound media upload '+Math.round(e.loaded/e.total*100)+'%')};xhr.upload.onload=()=>{done=true;clearInterval(timer)};xhr.onload=()=>{clearInterval(timer);if(xhr.status>=200&&xhr.status<300)resolve();else{let d;try{d=JSON.parse(xhr.responseText)}catch{}reject(Error(d?.message||d?.error||('Storage HTTP '+xhr.status)))}};xhr.onerror=()=>{clearInterval(timer);reject(Error('The upload connection failed before Storage returned a response'))};xhr.onabort=()=>{clearInterval(timer)};xhr.send(f)})}
const oldPublish=aaPublishBingoTopic;
aaPublishBingoTopic=async function(){if(!chosen)return oldPublish();try{if(!state.isLoggedIn||state.testMode)throw Error('Sound publishing requires a real signed-in Bingo account');if(state.wallPublishBusy)return;if(!processed){if(!await online())throw Error('The audio processor is not running yet. Your draft is retained; nothing was published.');const f=aaTopicMediaSelection()[0];if(!f||aaTopicMediaSelection().length!==1)throw Error('Select one photo or video for this sound');const caption=document.getElementById('topicBody')?.value.trim()||'';if(!caption)throw Error('Add your post text first');state.wallPublishBusy=true;render();try{const path=state.user.id+'/'+crypto.randomUUID()+'/'+String(f.name).replace(/[^a-zA-Z0-9._-]/g,'_');await upload(f,path);const r=await sb.rpc('bingo_queue_sound',{p_sound:chosen.id,p_path:path,p_caption:caption});if(r.error)throw r.error;toast('Media saved for processing. Open Sound processing to preview the completed file. Nothing has been published yet.','success')}finally{state.wallPublishBusy=false;render()}return}state.topicDraft.soundId=chosen.id;await oldPublish();if(!aaTopicMediaSelection().length){chosen=null;processed=false}}catch(e){fail(e)}};
const oldCancel=aaCancelWallComposer;aaCancelWallComposer=function(){chosen=null;processed=false;return oldCancel()};
const oldComposer=aaBingoTopicComposerHTML;aaBingoTopicComposerHTML=function(){return oldComposer().replace('<div class="details-actions" style="margin-top:8px">',composer()+'<div class="details-actions" style="margin-top:8px">')};
const oldCard=aaTopicPostCardHTML;aaTopicPostCardHTML=function(t){return oldCard(t).replace('<div class="bingo-topic-summary">',bar(t)+'<div class="bingo-topic-summary">')};
const oldFeed=aaMixedFeedTopicCardHTML;aaMixedFeedTopicCardHTML=function(c){return oldFeed(c).replace('<div class="aa-icon-action-row"',bar(c.source)+'<div class="aa-icon-action-row"')};
const oldViewer=aaOpenVideoLightbox;aaOpenVideoLightbox=function(src,title,id){oldViewer(src,title,id);const t=aaTopics().find(x=>String(x.id)===String(id));if(t)document.querySelector('#aaVideoLightbox .aa-lightbox-inner')?.insertAdjacentHTML('beforeend',bar(t))};
const oldLoad=aaLoadBingoWall;let wallLoadActive=false;aaLoadBingoWall=async function(){if(!sb||state.testMode||wallLoadActive)return;wallLoadActive=true;try{await oldLoad();await refresh();render()}catch(e){console.warn('Bingo sound catalogue unavailable',e?.message)}finally{wallLoadActive=false}};
window.BingoSounds={close:removeDialog,open,choose,capture,preview,playPreview,library,jobs,resume,posts,clear(){chosen=null;processed=false;state.topicDraft.soundId=null;render()},reload:async()=>{removeDialog();await aaLoadBingoWall()},bar,composer,version:'2026-10-01-integrated'};
if(sb)refresh().catch(()=>{});
})();
