/* Bingo public media: real cloud records, qualified counts and resilient autoplay. */
(function(){
'use strict';
if(window.BingoMedia)return;
// Retain old device-only submissions as owner drafts; never expose them as public cloud posts.
let legacy={jobs:[],parts:[]};try{legacy=JSON.parse(typeof aaStorage!=='undefined'?(aaStorage.get('bingo_device_category_drafts')||'{}'):'{}')}catch(e){}
const genuine=x=>/^[0-9a-f-]{36}$/i.test(String(x.userId||x.sellerId||x.ownerId||''));
legacy.jobs=[...(legacy.jobs||[]),...(state.jobs||[]).filter(x=>!x._fromDb&&genuine(x))];legacy.parts=[...(legacy.parts||[]),...(state.spareParts||[]).filter(x=>!x._fromDb&&genuine(x))];
legacy.jobs=[...new Map(legacy.jobs.map(x=>[String(x.id),x])).values()];legacy.parts=[...new Map(legacy.parts.map(x=>[String(x.id),x])).values()];
try{if(typeof aaStorage!=='undefined')aaStorage.set('bingo_device_category_drafts',JSON.stringify(legacy))}catch(e){}
function ownerDrafts(items,cloud){const ids=new Set(cloud.map(x=>String(x.id)));return items.filter(x=>state.isLoggedIn&&String(x.userId||x.sellerId||x.ownerId||'')===String(state.user?.id)&&!ids.has(String(x.id))).map(x=>({...x,_deviceOnly:true,_fromDb:false,status:'Draft on this device'}))}
const stats=new Map(),pending=new Set(),recording=new Set(),recorded=new Set();
let observer=null,measured=[],tick=null,categoryLoading=false,categoryFingerprint='',categoryLoadedAt=0,renderTimer=null;
let visitor;
try{visitor=localStorage.getItem('bingo_media_visitor');if(!/^[0-9a-f-]{36}$/i.test(visitor||'')){visitor=crypto.randomUUID();localStorage.setItem('bingo_media_visitor',visitor)}}catch(e){visitor=crypto.randomUUID()}
const type=t=>t==='stay'?'property':t==='food_business'?'food':t==='household'?'spare':t;
const key=(t,id)=>type(t)+':'+id;
function identity(el){const host=el.closest('[data-canon]');if(host){const value=host.dataset.canon,i=value.indexOf(':');return {type:type(value.slice(0,i)),id:value.slice(i+1),host}}if(el.dataset.aaPostId)return {type:type(el.dataset.aaPostType),id:el.dataset.aaPostId,host:el.closest('.aa360-item')||el.parentElement};return null}
function caption(row,video){return row?`${Number(row.view_count)} views · ${video?Number(row.watch_count)+' watched':Number(row.photo_count)+' photo views'}`:'Views — · '+(video?'Watched —':'Photo views —')}
function patchStats(){document.querySelectorAll('#auto-arcade-widget [data-bingo-stats]').forEach(el=>{el.textContent=caption(stats.get(el.dataset.bingoStats),el.dataset.video==='true')});document.querySelectorAll('#auto-arcade-widget .aa360-item[data-canon]').forEach(el=>{const row=stats.get(el.dataset.canon);const views=el.querySelector('.aa360-side button[aria-label="Views"]')?.parentElement?.querySelector('span');if(row&&views)views.textContent=typeof aaCompact==='function'?aaCompact(row.view_count):row.view_count})}
async function fetchStats(items,force=false){if(!sb||state.testMode)return;const want=items.filter(x=>x&&x.id&&!pending.has(key(x.type,x.id))&&(force||!stats.has(key(x.type,x.id)))).slice(0,100);if(!want.length)return;want.forEach(x=>pending.add(key(x.type,x.id)));try{const {data,error}=await sb.rpc('bingo_media_counts',{p_posts:want.map(x=>({type:type(x.type),id:x.id}))});if(error)throw error;(data||[]).forEach(x=>stats.set(key(x.post_type,x.post_id),x));patchStats()}catch(e){console.warn('Bingo media counts:',e?.message||e)}finally{want.forEach(x=>pending.delete(key(x.type,x.id)))}}
async function record(id,event){if(!sb||state.testMode||!id)return;const k=key(id.type,id.id)+':'+event;if(recorded.has(k)||recording.has(k))return;recording.add(k);try{const {error}=await sb.rpc('bingo_record_media_event',{p_type:type(id.type),p_id:id.id,p_visitor:visitor,p_event:event});if(error)throw error;recorded.add(k);await fetchStats([id],true)}catch(e){console.warn('Bingo view could not be saved:',e?.message||e)}finally{recording.delete(k)}}
function statsHTML(t,id,video,extra=''){const k=key(t,id);return `<span class="bingo-media-stats ${extra}" data-bingo-stats="${esc(k)}" data-video="${!!video}" title="Views: visible for 2 seconds. Watched: 3 seconds of playback. Counts deduplicate accounts or anonymous browsers.">${caption(stats.get(k),video)}</span>`}
function mediaError(v,error){const host=v.closest('.aa360-item')||v.parentElement;if(!host)return;let btn=host.querySelector('.bingo-media-retry');if(!btn){btn=document.createElement('button');btn.type='button';btn.className='btn bingo-media-retry';host.appendChild(btn)}const reason=error?.name==='NotAllowedError'?'Tap to play':v.error?.code===4?'Video format or source is unavailable':v.error?.code===3?'Video could not be decoded':v.error?.code===2?'Video transfer failed':'Video could not start';btn.textContent=reason+' · Retry';btn.onclick=e=>{e.stopPropagation();btn.remove();v.load();play(v,true)}}
function play(v,gesture=false){if(!v||!v.isConnected||aaHomeOverlayOpen())return;v.muted=!aaFeedWantsSound();v.playsInline=true;v.preload='auto';let p;try{p=v.play()}catch(e){mediaError(v,e);return}if(p?.catch)p.catch(e=>{if(e.name==='AbortError')return;if(e.name==='NotAllowedError'&&!v.muted){v.muted=true;state.aaFeedSoundOn=false;aaFeedUpdateSoundBtn();v.play()?.catch(next=>{if(next.name!=='AbortError')mediaError(v,next)})}else mediaError(v,e)})}
function activeVideo(){return document.querySelector('#auto-arcade-widget .aa360-item.bingo-media-active video.aa360-video')}
aaToggleFeedSound=function(){state.aaFeedSoundOn=!aaFeedWantsSound();const v=activeVideo();if(v)play(v,true);aaFeedUpdateSoundBtn()};
aaInit360Feed=function(){
 if(aaFeedObserver)aaFeedObserver.disconnect();
 const items=[...document.querySelectorAll('#auto-arcade-widget .aa360-feed .aa360-item')];if(!items.length)return;
 if(state.aaFeedSoundOn===undefined)state.aaFeedSoundOn=false;
 aaFeedObserver=new IntersectionObserver(entries=>{for(const entry of entries){const item=entry.target,v=item.querySelector('video.aa360-video');const visible=entry.isIntersecting&&entry.intersectionRatio>=.55;item.classList.toggle('bingo-media-active',visible);if(v){if(visible){items.forEach(other=>{if(other!==item)other.querySelector('video.aa360-video')?.pause()});play(v)}else v.pause()}}},{threshold:[0,.55,1]});
 items.forEach(item=>{aaFeedObserver.observe(item);const v=item.querySelector('video.aa360-video');if(v){v.addEventListener('error',()=>mediaError(v,v.error),{once:true});v.addEventListener('loadeddata',()=>{if(item.classList.contains('bingo-media-active'))play(v)},{once:true});v.addEventListener('playing',()=>item.querySelector('.bingo-media-retry')?.remove())}});
 aaFeedUpdateSoundBtn();
};
function measure(){if(observer)observer.disconnect();if(tick)clearInterval(tick);measured=[];const ids=[];
 observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{const m=measured.find(x=>x.el===entry.target);if(m){m.visible=entry.isIntersecting&&entry.intersectionRatio>=.5;m.lastTime=m.el instanceof HTMLVideoElement?m.el.currentTime:0}})},{threshold:[0,.5,1]});
 document.querySelectorAll('#auto-arcade-widget [data-canon],#aaVideoLightbox[data-canon],#aaPhotoLightbox[data-canon]').forEach(host=>{const media=[...host.querySelectorAll('video,img')].filter(el=>!el.closest('.aa-post-head,.aa360-seller,.aa-wall-author,.bingo-topic-comment,.bingo-topic-composer')&&!el.classList.contains('aa-post-avatar'));const el=media.find(x=>x.tagName==='VIDEO')||media[0];const id=el?identity(el):null;if(!el||!id)return;ids.push(id);measured.push({el,id,visible:false,exposure:0,watch:0,lastTime:el.currentTime||0});observer.observe(el)});
 fetchStats(ids);
 tick=setInterval(()=>{for(const m of measured){const v=m.el instanceof HTMLVideoElement;if(!m.el.isConnected||!m.visible||document.visibilityState!=='visible'||(aaHomeOverlayOpen()&&!m.el.closest('#aaVideoLightbox,#aaPhotoLightbox'))){m.lastTime=m.el.currentTime||0;continue}const loaded=v?m.el.readyState>=1:m.el.complete&&m.el.naturalWidth>0;if(!loaded)continue;m.exposure+=.25;if(m.exposure>=2){record(m.id,'view');if(!v)record(m.id,'photo')}if(v){const now=m.el.currentTime,delta=now-m.lastTime;if(!m.el.paused&&!m.el.seeking&&delta>0&&delta<1.5)m.watch+=Math.min(delta,.5);m.lastTime=now;if(m.watch>=3)record(m.id,'watch')}}},250);
}
const originalTile=aaBpTileHTML;
aaBpTileHTML=function(it,own){const html=originalTile(it,own);return html.replace('</div>',statsHTML(it.kind,it.id,!!it.video,'bingo-tile-stats')+'</div>')};
const originalTopicCard=aaTopicPostCardHTML;
aaTopicPostCardHTML=function(t){return originalTopicCard(t).replace('</article>',statsHTML('topic',t.id,(t.media||[]).some(m=>m.type==='video'))+'</article>')};
const originalMixedCard=aaMixedFeedCardHTML;
aaMixedFeedCardHTML=function(c,i){if(c.kind==='spare'||c.kind==='job')return extraFeedCard(c);const html=originalMixedCard(c,i),id=c.kind==='topic'?c._topicId:c._promoId||c.id;return html.replace('<div class="aa360-info"','<div class="aa360-info"').replace('</section>',statsHTML(c.kind,id,c.feed_media_type==='video'||c.kind==='vehicle'&&aaMediaType(c)==='video'||c.kind==='topic'&&c.feed_media_type==='video')+'</section>')};
function extraRows(){return [...(state.spareParts||[]).filter(x=>x._fromDb&&x.status==='published').map(x=>({kind:'spare',source:x,id:x.id})),...(state.jobs||[]).filter(x=>x._fromDb&&String(x.status).toLowerCase()==='published').map(x=>({kind:'job',source:x,id:x.id}))]}
function extraFeedCard(c){const x=c.source,id=String(x.id),owner=String(x.userId||x.sellerId||x.ownerId||''),meta=aaResolveMemberMeta(owner,x.sellerName||x.company||''),photo=(x.photos||[])[0]||'',kind=c.kind;return `<section class="aa360-item" data-aa-feed-id="${esc(id)}_${kind}" data-canon="${kind}:${esc(id)}">${photo?`<img class="aa360-video" src="${bingoSafeMediaAttr(photo)}" alt="${esc(x.title)}">`:`<div class="aa360-video aa360-text-hero">${esc(x.title)}</div>`}<div class="aa360-shade"></div><div class="aa360-info"><div class="aa360-seller-wrap"><button class="aa360-seller" onclick='openSeller(${JSON.stringify(owner)})'><img src="${bingoSafeMediaAttr(aaProfilePhoto(meta.photo))}" onerror="aaProfileImgFallback(this)"><span><b>${esc(aaMemberDisplayName(meta))}</b><small>${esc(x.town||x.county||'Kenya')}</small></span></button></div><span class="badge badge-gold">${kind==='job'?'JOB':x.listingType==='household'?'HOUSEHOLD ITEM':'SPARE PART'}</span><div class="aa360-title">${esc(x.title)}</div>${x.price?`<div class="aa360-price">KES ${money(x.price)}</div>`:''}<div class="aa360-desc">${aaFeedDescExcerptHTML(x.description||'')}</div><div class="aa360-actions"><button class="bingo-neon-action bingo-neon-action-gold" onclick='aaCanonOpen(${JSON.stringify(kind)},${JSON.stringify(id)})'>View ${kind==='job'?'Job':'Item'}</button></div></div>${statsHTML(kind,id,false)}</section>`}
const originalPartFilter=aaPartFiltered;aaPartFiltered=function(){return originalPartFilter().filter(x=>x._fromDb&&x.status==='published'||x._deviceOnly&&state.isLoggedIn&&String(x.sellerId||x.userId)===String(state.user?.id))};
const originalActiveFood=aaFoodActive;aaFoodActive=function(f){return String(f?.status||'').toLowerCase()==='published'&&originalActiveFood(f)};
const originalFoods=aaFoods;aaFoods=function(){return state.testMode?originalFoods():Array.isArray(state.foodBusinesses)?state.foodBusinesses:[]};
const originalMixedItems=aaMixedFeedItems;
aaMixedFeedItems=function(){const all=[...originalMixedItems(),...extraRows().map(c=>({...c,id:c.id+'_'+c.kind,feed_title:c.source.title,feed_desc:c.source.description,feed_media:(c.source.photos||[])[0]||'',feed_media_type:'image',created_at:c.source.createdAt,_promoId:c.source.id}))];return all.filter(c=>state.homeMediaFilter!=='videos'||(c.kind==='vehicle'?aaMediaType(c)==='video':c.feed_media_type==='video'||c.kind==='food'&&!!c.feed_media)).filter(c=>state.homeMediaFilter!=='photos'||(c.kind==='vehicle'?aaMediaType(c)==='photo':c.feed_media_type!=='video')).filter(c=>state.feedFilter!=='following'||aaIsFollowing(c.feed_sellerId||c.sellerId||c.source?.userId||c.source?.sellerId||c.source?.authorId)).sort((a,b)=>new Date(b.created_at||b.createdAt||0)-new Date(a.created_at||a.createdAt||0))};
const originalCanonOpen=aaCanonOpen;
aaCanonOpen=function(t,id){if(t==='spare'){aaOpenSpareDetails(id);return}if(t==='job'){openJob(id);return}originalCanonOpen(t,id)};
const originalBpItems=aaBpItems;
aaBpItems=function(s,cars,owner){return [...originalBpItems(s,(cars||[]).filter(x=>!x._localDemo),owner),...extraRows().filter(c=>String(c.source.userId||c.source.sellerId||c.source.ownerId)===String(owner)).map(c=>({kind:c.kind,id:String(c.id),title:c.source.title,img:(c.source.photos||[])[0]||'',video:'',at:c.source.createdAt,open:`aaCanonOpen(${JSON.stringify(c.kind)},${JSON.stringify(String(c.id))})`}))].sort((a,b)=>new Date(b.at||0)-new Date(a.at||0))};
for(const [name,kind] of [['cardHTML','vehicle'],['aaVideoGridCardHTML','vehicle'],['aaProfileMiniCardHTML','vehicle'],['aaPartCardHTML','spare'],['aaProfilePropertyCardHTML','property'],['aaProfileFoodCardHTML','food']]){const original=window[name];if(typeof original!=='function')continue;window[name]=function(item){let html=original.apply(this,arguments);if(!item?.id)return html;html=html.replace(/^(\s*<(?:article|div|section)\b)/,'$1 data-canon="'+kind+':'+esc(String(item.id))+'"');const video=kind==='vehicle'?aaMediaType(item)==='video':(item.media||[]).some(m=>m.type==='video');const end=Math.max(html.lastIndexOf('</article>'),html.lastIndexOf('</div>'));if(end>=0)html=html.slice(0,end)+(!item._deviceOnly?statsHTML(kind,item.id,video):'<span class="bingo-media-stats">Draft saved on this device</span>')+html.slice(end);return html}}
const originalSeller=window.sellerHTML;
window.sellerHTML=function(s,cars){const html=originalSeller(s,cars);if(state.isLoggedIn)return html;const owner=String(s?.sellerId||s?.userId||s?.id||''),items=aaBpItems(s,cars,owner).filter(x=>!x.draft);return html.replace('</section>','<div class="bp-page"><div class="bp-subhead">Public posts</div>'+(items.length?'<div class="bp-grid">'+items.map(x=>aaBpTileHTML(x,false)).join('')+'</div>':'<div class="bp-empty">No public posts yet.</div>')+'</div></section>')};
const originalWall=aaPublicTopicsFeedHTML;
aaPublicTopicsFeedHTML=function(){const html=originalWall();const entries=[...(state.listings||[]).filter(x=>!x._localDemo&&x._fromDb&&['available','published'].includes(x.status)).map(x=>({kind:'vehicle',source:x})),...aaProperties().filter(x=>x.status==='published').map(x=>({kind:'property',source:x})),...aaFoods().filter(aaFoodActive).map(x=>({kind:'food',source:x})),...extraRows()];const cards=entries.map(c=>c.kind==='spare'||c.kind==='job'?extraFeedCard(c):aaWallListingCardHTML(c.kind,c.source).replace('</article>',statsHTML(c.kind,c.source.id,(c.kind==='vehicle'?aaMediaType(c.source)==='video':(c.source.media||[]).some(m=>m.type==='video')))+'</article>')).join('');return html.replace('</section>',cards+'</section>')};
function categoryMap(row,urls=[]){const x={...row.payload,id:row.id,userId:row.user_id,ownerId:row.user_id,sellerId:row.user_id,createdAt:row.created_at,updatedAt:row.updated_at,status:row.status,_fromDb:true};if(row.category==='job')x.status=row.status[0].toUpperCase()+row.status.slice(1);else x.photos=urls;return x}
async function loadCategories(){if(!sb||state.testMode||categoryLoading)return;categoryLoading=true;try{const {data,error}=await sb.from('bingo_category_listings').select('*').order('created_at',{ascending:false});if(error)throw error;const fingerprint=String(state.user?.id||'')+':'+JSON.stringify(data||[]);if(fingerprint===categoryFingerprint&&Date.now()-categoryLoadedAt<3000000)return;let mediaFailed=false;const mapped=await Promise.all((data||[]).map(async row=>{const paths=Array.isArray(row.payload.photoPaths)?row.payload.photoPaths.filter(p=>typeof p==='string'&&p.startsWith(row.user_id+'/'+row.id+'/')&&p.length<700):[];const urls=await Promise.all(paths.map(async path=>{const {data,error}=await sb.storage.from('category-media').createSignedUrl(path,3600);if(error){mediaFailed=true;console.warn('Bingo category media:',error.message);return ''}return data.signedUrl}));return {row,item:categoryMap(row,urls.filter(Boolean))}}));const jobs=mapped.filter(x=>x.row.category==='job').map(x=>x.item),parts=mapped.filter(x=>x.row.category!=='job').map(x=>x.item);state.jobs=[...jobs,...ownerDrafts(legacy.jobs,jobs)];state.spareParts=[...parts,...ownerDrafts(legacy.parts,parts)];categoryFingerprint=mediaFailed?'':fingerprint;categoryLoadedAt=Date.now();render()}catch(e){console.warn('Bingo category listings:',e?.message||e)}finally{categoryLoading=false}}
async function putCategory(category,item){if(!sb)throw new Error('Cloud connection unavailable.');const {data:auth,error:authError}=await sb.auth.getUser();if(authError||!auth?.user)throw new Error('Please sign in again before publishing.');const uid=auth.user.id;if(String(item.userId||item.sellerId||item.ownerId)!==uid)throw new Error('Only the owner may change this listing.');const payload={...item};delete payload.photos;delete payload._fromDb;const status=String(item.status||'published').toLowerCase();const {data,error}=await sb.from('bingo_category_listings').upsert({id:String(item.id),user_id:uid,category,status,payload,updated_at:new Date().toISOString()}).select('id').single();if(error||!data)throw error||new Error('The listing was not saved.');categoryFingerprint='';await loadCategories()}
aaPublishSparePart=async function(){if(!state.isLoggedIn){openAuth('register');return}if(state.categoryPublishBusy)return;const get=id=>String(document.getElementById(id)?.value||'').trim(),files=[...document.getElementById('spPhotos').files],household=get('spListingType')==='household',price=Number(get('spPrice')),uid=state.user.id,id=crypto.randomUUID();if(!get('spTitle')||!price||!get('spCounty')||!get('spTown')||!get('spStore')||!normalizeKenyanPhone(get('spPhone'))){toast('Complete title, price, seller, location and phone.');return}if(!household&&(!get('spMake')||!get('spModel')||!get('spYears'))){toast('Add make, model and compatible years.');return}if(!files.length||files.length>6){toast('Choose 1–6 photos.');return}if(files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>20971520)){toast('Use JPG, PNG or WebP photos up to 20 MB each.');return}state.categoryPublishBusy=true;const paths=[];try{for(let i=0;i<files.length;i++){const path=uid+'/'+id+'/'+Date.now()+'-'+i+'.'+files[i].name.split('.').pop();const {error}=await aaUploadStorageWithFeedback('category-media',path,files[i],{upsert:false,contentType:files[i].type});if(error)throw error;paths.push(path)}const x={id,sellerId:uid,userId:uid,title:get('spTitle'),listingType:household?'household':'spare_parts',category:household?get('spCategoryHousehold'):get('spCategory'),householdCategory:household?get('spCategoryHousehold'):'',condition:get('spCondition'),brand:get('spBrand'),dimensions:get('spDimensions'),make:get('spMake'),model:get('spModel'),yearRange:get('spYears'),engineChassis:get('spEngine'),oem:get('spOem'),price,negotiable:!!document.getElementById('spNegotiable')?.checked,county:get('spCounty'),town:get('spTown'),area:get('spArea'),storeName:get('spStore'),building:get('spBuilding'),pickup:!!document.getElementById('spPickup')?.checked,shipping:!!document.getElementById('spShipping')?.checked,description:get('spDescription'),sellerPhone:normalizeKenyanPhone(get('spPhone')),sellerName:aaOwnProfileName(),photoPaths:paths,status:'published'};await putCategory(household?'household':'spare',x);aaOpenSpareDetails(id);toast('Item saved to Bingo and published.')}catch(e){toast('Could not publish item: '+(e?.message||e));if(paths.length)await sb.storage.from('category-media').remove(paths)}finally{state.categoryPublishBusy=false}};
publishVacancyRecord=async function(){if(!state.isLoggedIn){openAuth('register');return}if(state.categoryPublishBusy)return;const get=id=>document.getElementById(id)?.value?.trim()||'',title=get('vacTitle'),company=get('vacCompany'),description=get('vacDescription');if(!title||!company||!description){toast('Complete job title, company and description.');return}const old=state.editingJobId?(state.jobs||[]).find(j=>String(j.id)===String(state.editingJobId)):null;if(old&&!aaIsOwnJob(old)){toast('Only the owner can edit this vacancy.');return}state.categoryPublishBusy=true;try{await putCategory('job',{...old,id:old?.id||crypto.randomUUID(),userId:state.user.id,ownerId:state.user.id,title,company,description,county:get('vacCounty'),experience:get('vacExperience'),status:old?._deviceOnly?'Published':old?.status||'Published'});state.editingJobId=null;state.jobsTab='myjobs';render();toast('Vacancy saved to Bingo.')}catch(e){toast('Could not save vacancy: '+(e?.message||e))}finally{state.categoryPublishBusy=false}};
async function jobStatus(id,status){const j=(state.jobs||[]).find(x=>String(x.id)===String(id));if(!j||!aaIsOwnJob(j)){toast('Only the owner can change this vacancy.');return}try{await putCategory('job',{...j,status});render()}catch(e){toast('Could not change vacancy: '+(e?.message||e))}}
toggleOwnJobPause=id=>{const j=(state.jobs||[]).find(x=>String(x.id)===String(id));return jobStatus(id,String(j?.status).toLowerCase()==='paused'?'published':'paused')};archiveOwnJob=id=>jobStatus(id,'archived');
deleteOwnJob=async function(id){const j=(state.jobs||[]).find(x=>String(x.id)===String(id));if(!j||!aaIsOwnJob(j)){toast('Only the owner can delete this vacancy.');return}if(!confirm('Delete this job permanently?'))return;try{const {data,error}=await sb.from('bingo_category_listings').delete().eq('id',String(id)).eq('user_id',state.user.id).select('id');if(error||!data?.length)throw error||new Error('Job was not deleted.');categoryFingerprint='';await loadCategories();state.selectedJob=null;state.view='jobs';state.jobsTab='myjobs';render()}catch(e){toast('Could not delete job: '+(e?.message||e))}};
function detailWrap(fn,t,get){return function(){const x=get.apply(this,arguments);const html=fn.apply(this,arguments);if(!x?.id)return html;return '<div data-canon="'+t+':'+esc(String(x.id))+'">'+html+statsHTML(t,x.id,t==='vehicle'?aaMediaType(x)==='video':(x.media||[]).some(m=>m.type==='video'))+'</div>'}}
detailsHTML=detailWrap(detailsHTML,'vehicle',x=>x);
aaPropertyDetailHTML=detailWrap(aaPropertyDetailHTML,'property',x=>x);
aaSpareDetailsHTML=detailWrap(aaSpareDetailsHTML,'spare',x=>x);
jobHTML=detailWrap(jobHTML,'job',x=>x);
// Food has its own business id in state rather than a function argument.
aaFoodBusinessProfileHTML=detailWrap(aaFoodBusinessProfileHTML,'food',()=>aaFoods().find(x=>String(x.id)===String(state.foodBusinessProfileId||state.foodProfileId||state.foodSelectedBusinessId)));
function sourceIdentity(src,id){const topic=aaTopics().find(t=>String(t.id)===String(id)||(t.media||[]).some(m=>aaTopicMediaSrc(m)===src));if(topic)return {type:'topic',id:topic.id};const vehicle=(state.listings||[]).find(x=>aaVideoUrl(x)===src||(x.images||[]).includes(src)||x.image===src);if(vehicle)return {type:'vehicle',id:vehicle.id};for(const [kind,rows] of [['property',aaProperties()],['food',aaFoods()]]){const found=rows.find(x=>(x.media||[]).some(m=>m.url===src));if(found)return {type:kind,id:found.id}}return null}
const originalVideoOpen=aaOpenVideoLightbox;
aaOpenVideoLightbox=function(src,title,id){originalVideoOpen(src,title,id);const box=document.getElementById('aaVideoLightbox'),source=sourceIdentity(src,id);if(box&&source){box.dataset.canon=key(source.type,source.id);box.querySelector('.aa-lightbox-inner')?.insertAdjacentHTML('beforeend',statsHTML(source.type,source.id,true));measure()}};
const originalPhotoOpen=aaOpenPhotoLightbox;
aaOpenPhotoLightbox=function(src,title,id){originalPhotoOpen(src,title,id);aaPauseAllFeedVideos();const box=document.getElementById('aaPhotoLightbox'),source=sourceIdentity(src,id);if(box&&source){box.dataset.canon=key(source.type,source.id);box.querySelector('.aa-lightbox-inner')?.insertAdjacentHTML('beforeend',statsHTML(source.type,source.id,false));measure()}};
const originalOverlay=aaHomeOverlayOpen;
aaHomeOverlayOpen=function(){return originalOverlay()||!!document.getElementById('aaVideoLightbox')||!!document.getElementById('aaPhotoLightbox')||!!document.getElementById('bingoSoundDialog')};
new MutationObserver(()=>{if(aaHomeOverlayOpen())aaPauseAllFeedVideos();else if(state.view==='home')aaInit360Feed()}).observe(document.body,{childList:true});
const originalRender=render;
render=function(){const feed=document.querySelector('#auto-arcade-widget .aa360-feed'),scroll=feed?.scrollTop||0;const playing=[...document.querySelectorAll('#auto-arcade-widget video.aa360-video')].map(v=>({id:identity(v),time:v.currentTime}));originalRender.apply(this,arguments);const next=document.querySelector('#auto-arcade-widget .aa360-feed');if(feed&&next)next.scrollTop=scroll;for(const saved of playing){if(!saved.id||!saved.time)continue;const host=[...document.querySelectorAll('#auto-arcade-widget [data-canon]')].find(x=>x.dataset.canon===key(saved.id.type,saved.id.id)),v=host?.querySelector('video.aa360-video');if(v){const restore=()=>{if(saved.time<v.duration)v.currentTime=saved.time};if(v.readyState>=1)restore();else v.addEventListener('loadedmetadata',restore,{once:true})}}clearTimeout(renderTimer);renderTimer=setTimeout(()=>{measure();patchStats()},0)};
const originalLoad=aaLoadVehicles;
aaLoadVehicles=async function(){await originalLoad.apply(this,arguments);await Promise.allSettled([loadCategories(),aaLoadProperties(),aaLoadFoods()])};
// Purge legacy sample and local-only public records. Unsaved forms remain drafts.
state.listings=(state.listings||[]).filter(x=>!x._localDemo&&x._fromDb&&/^[0-9a-f-]{36}$/i.test(String(x.id)));
state.jobs=ownerDrafts(legacy.jobs,[]);state.spareParts=ownerDrafts(legacy.parts,[]);
window.BingoMedia={version:'2026-10-01-public-media',loadCategories,fetchStats,record,statsHTML};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')aaPauseAllFeedVideos();else if(state.view==='home')aaInit360Feed()});
setInterval(()=>{if(document.visibilityState==='visible'&&sb&&!state.testMode)loadCategories()},60000);
})();
