import { createClient } from "npm:@supabase/supabase-js@2";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const need=(n:string)=>{const v=Deno.env.get(n);if(!v)throw new Error("Missing "+n);return v};
const env=(Deno.env.get("MPESA_ENVIRONMENT")||"sandbox").toLowerCase(),base=env==="production"?"https://api.safaricom.co.ke":"https://sandbox.safaricom.co.ke",prices:any={bronze:5,silver:25,gold:50};
function phone(v:any){let p=String(v||"").replace(/[^\d+]/g,"");if(p[0]==="+")p=p.slice(1);if(p[0]==="0")p="254"+p.slice(1);if(/^7\d{8}$/.test(p))p="254"+p;return /^254[17]\d{8}$/.test(p)?p:null}
function admin(){let key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!key){try{const keys=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}");key=keys.default||keys["default"]}catch{}}if(!key)throw new Error("Missing Supabase server secret key");return createClient(need("SUPABASE_URL"),key,{auth:{persistSession:false,autoRefreshToken:false}})}
function ts(){const d=new Date(Date.now()+10800000),z=(n:number)=>String(n).padStart(2,"0");return d.getUTCFullYear()+z(d.getUTCMonth()+1)+z(d.getUTCDate())+z(d.getUTCHours())+z(d.getUTCMinutes())+z(d.getUTCSeconds())}
async function token(){const r=await fetch(base+"/oauth/v1/generate?grant_type=client_credentials",{headers:{Authorization:"Basic "+btoa(need("MPESA_CONSUMER_KEY")+":"+need("MPESA_CONSUMER_SECRET"))}}),j=await r.json();if(!r.ok||!j.access_token)throw new Error("M-Pesa OAuth failed");return j.access_token}
async function stk(p:string,a:number,ref:string){const sc=need("MPESA_SHORTCODE"),stamp=ts(),pass=btoa(sc+need("MPESA_PASSKEY")+stamp),cb=need("SUPABASE_URL")+"/functions/v1/mpesa-crown?callback=1";const r=await fetch(base+"/mpesa/stkpush/v1/processrequest",{method:"POST",headers:{Authorization:"Bearer "+await token(),"Content-Type":"application/json"},body:JSON.stringify({BusinessShortCode:Number(sc),Password:pass,Timestamp:stamp,TransactionType:"CustomerPayBillOnline",Amount:a,PartyA:Number(p),PartyB:Number(sc),PhoneNumber:Number(p),CallBackURL:cb,AccountReference:ref,TransactionDesc:"Bingo crown award"})}),j=await r.json();if(!r.ok||String(j.ResponseCode)!=="0")throw new Error(j.errorMessage||j.CustomerMessage||"M-Pesa STK Push failed");return j}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("",{headers:H});const u=new URL(req.url),db=admin();
if(u.searchParams.get("callback")==="1"){const b=await req.json().catch(()=>({})),c=b?.Body?.stkCallback,checkout=String(c?.CheckoutRequestID||"");if(!checkout)return out({ok:true});const rc=Number(c?.ResultCode),items=c?.CallbackMetadata?.Item||[],val=(n:string)=>items.find((x:any)=>x.Name===n)?.Value??null,{data:p}=await db.from("bingo_crown_purchases").select("*").eq("checkout_request_id",checkout).maybeSingle();if(!p)return out({ok:true});if(rc===0){await db.from("bingo_crown_purchases").update({payment_status:"paid",mpesa_receipt:val("MpesaReceiptNumber"),result_code:0,result_description:c?.ResultDesc||null,raw_callback:b,paid_at:new Date().toISOString()}).eq("id",p.id).neq("payment_status","paid");await db.from("bingo_crown_awards").upsert({purchase_id:p.id,giver_id:p.buyer_id,recipient_id:p.recipient_id,topic_id:p.topic_id,crown_type:p.crown_type,amount_paid:p.amount},{onConflict:"purchase_id",ignoreDuplicates:true})}else await db.from("bingo_crown_purchases").update({payment_status:"failed",result_code:rc,result_description:c?.ResultDesc||null,raw_callback:b}).eq("id",p.id).neq("payment_status","paid");return out({ok:true})}
const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out({ok:false,error:"Sign in required"},401);const {data:{user},error}=await db.auth.getUser(auth.slice(7));if(error||!user)return out({ok:false,error:"Invalid session"},401);
const b=await req.json().catch(()=>({})),type=String(b.crown_type||"").toLowerCase(),amount=prices[type],recipient=String(b.recipient_id||""),topic=b.topic_id?String(b.topic_id):null,p=phone(b.phone);if(!amount)return out({ok:false,error:"Choose Bronze, Silver or Gold"},400);if(!p)return out({ok:false,error:"Enter a valid Kenyan M-Pesa number"},400);if(!recipient)return out({ok:false,error:"recipient_id is required"},400);if(recipient===user.id)return out({ok:false,error:"Crowns are awarded to another member"},400);
const {data:rp}=await db.from("profiles").select("id").eq("id",recipient).maybeSingle();if(!rp)return out({ok:false,error:"Recipient not found"},404);if(topic){const {data:t}=await db.from("bingo_topics").select("id,user_id").eq("id",topic).maybeSingle();if(!t||String(t.user_id)!==recipient)return out({ok:false,error:"Post recipient mismatch"},400)}
const {data:purchase,error:pe}=await db.from("bingo_crown_purchases").insert({buyer_id:user.id,recipient_id:recipient,topic_id:topic,crown_type:type,amount,phone:p}).select().single();if(pe)return out({ok:false,error:"Could not create crown purchase"},500);
try{const s=await stk(p,amount,"CROWN-"+String(purchase.id).slice(0,12));await db.from("bingo_crown_purchases").update({payment_status:"stk_sent",merchant_request_id:s.MerchantRequestID||null,checkout_request_id:s.CheckoutRequestID||null}).eq("id",purchase.id);return out({ok:true,purchase_id:purchase.id,crown_type:type,amount,message:s.CustomerMessage||"M-Pesa prompt sent"})}catch(e){await db.from("bingo_crown_purchases").update({payment_status:"failed",result_description:String(e)}).eq("id",purchase.id);return out({ok:false,error:e instanceof Error?e.message:"Unable to send M-Pesa prompt"},502)}});